//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPS_WSP_WinForm_CSharp.MPSWebService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mercurypay.com", ConfigurationName="MPSWebService.wsSoap")]
    public interface wsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CBatch(string merchant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CBatch", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> CBatchAsync(string merchant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AllowRunAsDebit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AllowRunAsDebit(string merchant, string pw, string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AllowRunAsDebit", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AllowRunAsDebitAsync(string merchant, string pw, string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CTranDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CTranDetail(string merchant, string pw, string invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CTranDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CTranDetailAsync(string merchant, string pw, string invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllDetail(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CAllDetailAsync(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetailEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllDetailEx(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetailEx", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CAllDetailExAsync(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllGiftDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllGiftDetail(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllGiftDetail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CAllGiftDetailAsync(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreditTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> CreditTransactionAsync(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/GiftTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GiftTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/GiftTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GiftTransactionAsync(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/LoyaltyTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoyaltyTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/LoyaltyTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LoyaltyTransactionAsync(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/ACHTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ACHTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/ACHTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ACHTransactionAsync(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/ACHStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ACHStatus(string merchant, string pw, string invoice, string startdate, string enddate, string fundingStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/ACHStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ACHStatusAsync(string merchant, string pw, string invoice, string startdate, string enddate, string fundingStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AssociateAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AssociateAccount(string account, string identifier, string merchantid, string memo, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AssociateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> AssociateAccountAsync(string account, string identifier, string merchantid, string memo, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/RemoveAccountAssociation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RemoveAccountAssociation(string account, string identifier, string merchantid, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/RemoveAccountAssociation", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RemoveAccountAssociationAsync(string account, string identifier, string merchantid, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/Lookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Lookup(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/Lookup", ReplyAction="*")]
        System.Threading.Tasks.Task<string> LookupAsync(string tran, string pw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSoapChannel : MPS_WSP_WinForm_CSharp.MPSWebService.wsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSoapClient : System.ServiceModel.ClientBase<MPS_WSP_WinForm_CSharp.MPSWebService.wsSoap>, MPS_WSP_WinForm_CSharp.MPSWebService.wsSoap {
        
        public wsSoapClient() {
        }
        
        public wsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet CBatch(string merchant) {
            return base.Channel.CBatch(merchant);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CBatchAsync(string merchant) {
            return base.Channel.CBatchAsync(merchant);
        }
        
        public bool AllowRunAsDebit(string merchant, string pw, string account) {
            return base.Channel.AllowRunAsDebit(merchant, pw, account);
        }
        
        public System.Threading.Tasks.Task<bool> AllowRunAsDebitAsync(string merchant, string pw, string account) {
            return base.Channel.AllowRunAsDebitAsync(merchant, pw, account);
        }
        
        public string CTranDetail(string merchant, string pw, string invoice) {
            return base.Channel.CTranDetail(merchant, pw, invoice);
        }
        
        public System.Threading.Tasks.Task<string> CTranDetailAsync(string merchant, string pw, string invoice) {
            return base.Channel.CTranDetailAsync(merchant, pw, invoice);
        }
        
        public string CAllDetail(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllDetail(merchant, pw, invoice, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<string> CAllDetailAsync(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllDetailAsync(merchant, pw, invoice, startdate, enddate);
        }
        
        public string CAllDetailEx(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode) {
            return base.Channel.CAllDetailEx(merchant, pw, invoice, startdate, enddate, transactioncode);
        }
        
        public System.Threading.Tasks.Task<string> CAllDetailExAsync(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode) {
            return base.Channel.CAllDetailExAsync(merchant, pw, invoice, startdate, enddate, transactioncode);
        }
        
        public string CAllGiftDetail(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllGiftDetail(merchant, pw, invoice, startdate, enddate);
        }
        
        public System.Threading.Tasks.Task<string> CAllGiftDetailAsync(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllGiftDetailAsync(merchant, pw, invoice, startdate, enddate);
        }
        
        public string CreditTransaction(string tran, string pw) {
            return base.Channel.CreditTransaction(tran, pw);
        }
        
        public System.Threading.Tasks.Task<string> CreditTransactionAsync(string tran, string pw) {
            return base.Channel.CreditTransactionAsync(tran, pw);
        }
        
        public string GiftTransaction(string tran, string pw) {
            return base.Channel.GiftTransaction(tran, pw);
        }
        
        public System.Threading.Tasks.Task<string> GiftTransactionAsync(string tran, string pw) {
            return base.Channel.GiftTransactionAsync(tran, pw);
        }
        
        public string LoyaltyTransaction(string tran, string pw) {
            return base.Channel.LoyaltyTransaction(tran, pw);
        }
        
        public System.Threading.Tasks.Task<string> LoyaltyTransactionAsync(string tran, string pw) {
            return base.Channel.LoyaltyTransactionAsync(tran, pw);
        }
        
        public string ACHTransaction(string tran, string pw) {
            return base.Channel.ACHTransaction(tran, pw);
        }
        
        public System.Threading.Tasks.Task<string> ACHTransactionAsync(string tran, string pw) {
            return base.Channel.ACHTransactionAsync(tran, pw);
        }
        
        public string ACHStatus(string merchant, string pw, string invoice, string startdate, string enddate, string fundingStatus) {
            return base.Channel.ACHStatus(merchant, pw, invoice, startdate, enddate, fundingStatus);
        }
        
        public System.Threading.Tasks.Task<string> ACHStatusAsync(string merchant, string pw, string invoice, string startdate, string enddate, string fundingStatus) {
            return base.Channel.ACHStatusAsync(merchant, pw, invoice, startdate, enddate, fundingStatus);
        }
        
        public bool AssociateAccount(string account, string identifier, string merchantid, string memo, string pw) {
            return base.Channel.AssociateAccount(account, identifier, merchantid, memo, pw);
        }
        
        public System.Threading.Tasks.Task<bool> AssociateAccountAsync(string account, string identifier, string merchantid, string memo, string pw) {
            return base.Channel.AssociateAccountAsync(account, identifier, merchantid, memo, pw);
        }
        
        public bool RemoveAccountAssociation(string account, string identifier, string merchantid, string pw) {
            return base.Channel.RemoveAccountAssociation(account, identifier, merchantid, pw);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveAccountAssociationAsync(string account, string identifier, string merchantid, string pw) {
            return base.Channel.RemoveAccountAssociationAsync(account, identifier, merchantid, pw);
        }
        
        public string Lookup(string tran, string pw) {
            return base.Channel.Lookup(tran, pw);
        }
        
        public System.Threading.Tasks.Task<string> LookupAsync(string tran, string pw) {
            return base.Channel.LookupAsync(tran, pw);
        }
    }
}
